spring.thymeleaf.prefix=/WEB-INF/views/
spring.thymeleaf.suffix=.html

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

spring.security.oauth2.client.registration.google.client-id=390468462355-605umotentpl4jqu1pqdh57f6351lsv6.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

spring.security.oauth2.client.registration.facebook.client-id=1454809475067563
spring.security.oauth2.client.registration.facebook.client-secret=3772cff445dac91e05f0b17c59d32def
spring.security.oauth2.client.registration.facebook.redirect-uri=http://localhost:8080/login/oauth2/code/facebook

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/qlsb
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql: true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=maousama333@gmail.com
spring.mail.password=fctf xrat bqse kwll
spring.mail.properties.mail.smpt.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true