name: CICD FE Pipeline

on:
  push:
    branches: [fe-deployment]

permissions:
  contents: read  
  pages: write      
  id-token: write  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source  
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
            node-version: 20
      - name: Install Dependencies
        run: npm ci
      - name: Build Project
        run: npm run build      
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3   
        with:
           name: 'github-pages'
           path: build
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: 'github-pages'
