name: CICD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '21'
      - name: Build Project
        run: mvn -f BE/httc-sport/pom.xml clean package -DskipTests
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker Image
        run: docker build -t naut2802/httc-sport BE/httc-sport
      - name: Publish image to Docker Hub
        run: docker image push naut2802/httc-sport:latest
  deploy:
    needs: build
    runs-on: [self-hosted, aws-ec2]
    steps:
      - name: Set up Docker on EC2
        run: |
          sudo yum update -y
          sudo amazon-linux-extras install docker -y
          sudo service docker start
          sudo systemctl enable docker
          sudo usermod -a -G docker $USER
          newgrp docker
      - name: Verify Docker is running
        run: sudo systemctl status docker
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Pull Image from Docker Hub
        run: docker pull naut2802/httc-sport:latest
      - name: Delete old container
        run: docker rm -f httc-sport-container
      - name: Create .env file from secret
        run: echo "${{ secrets.ENV }}" >> /home/linux/app/.env
      - name: Run docker container
        run: docker run --env-file /home/linux/app/.env \
            --restart unless-stopped -d -p 8082:8082 \
            --name httc-sport-container naut2802/httc-sport:latest
